### ISSUE TITLE
own webcam stream shown partially out of screen

### ISSUE THREAD

**Issue by micheleb** [appearin/appearin-sdk#12]
I don't know if this is the right place to post this, so apologies if it should be reported somewhere else.

It looks like something changed in the `iframe` source in the recent weeks, resulting in this being how our embedded appear.in panel looks like when waiting for other clients to join:

![the iframe](https://cloud.githubusercontent.com/assets/1333955/16071980/9f97305e-32de-11e6-8dca-69adf7f42228.png)

Before this recent change, the webcam video stream would show up at the top of the frame instead.

**Comment by csdodd** [comment]
I'm on the case
![image](https://media.giphy.com/media/QC9MRxmLskle8/giphy.gif)

**Comment by csdodd** [comment]
Should be fixed -- let me know if you're still seeing issues.

**Comment by micheleb** [comment]
perfect, that fixed it, thanks!
