### ISSUE TITLE
recent room list takes up most iframe

### ISSUE THREAD

**Issue by micheleb** [appearin/appearin-sdk#15]
on narrow iframes, the new "recently visited" list of chatrooms takes up most of the space. Would it be possible to hide it when loaded through the SDK?

![room-list](https://cloud.githubusercontent.com/assets/1333955/16344397/a46d8d0c-3a3c-11e6-951d-d43ab91066c9.png)

**Comment by sveinw** [comment]
Hi Michele,

We have already removed the room list on the embedded version. This will be live on the next deploy.

-- Svein, appear.in

**Comment by micheleb** [comment]
awesome, thanks! 

On Jun 25, 2016, Svein Willassen <notifications@github.com> wrote:
>Hi Michele,
>
>We have already removed the room list on the embedded version. This
>will be live on the next deploy.
>
>-- Svein, appear.in
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/appearin/appearin-sdk/issues/15#issuecomment-228562811

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.
